# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Bich Ngoc (Rubi) Doan
description: Rubi's website.
baseurl: ""
url: "https://ngoccc.github.io"
og_image: /assets/img/profile-pic.jpg
google_analytics: "G-2Y51DWRKJB"

header:
  pages:
    - name: Home
      slug: /
    - name: Publications
    - name: Personal
    - name: CV
      slug: /assets/pdf/cv/resume-250606.pdf

footer:
  show_powered_by: true
  contact:
    - type: email
      name: bich.doan@epfl.ch
      value: bich.doan@epfl.ch
#    - type: wechat
#      value: YourWeChatUsername
#      link: "#"
  follow:
    - type: twitter
      name: Twitter
      link: https://x.com/ngowojc
      username: "@ngowojc"
#    - type: facebook
#      name: Facebook
#      link: http://facebook.com/YourFacebookUsername
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/ngocdb169
    - type: github
      name: GitHub
      link: http://github.com/ngoccc
#    - type: dribbble
#      name: Dribbble
#      link: https://dribbble.com/YourDribbbleUsername
#    - type: rss
#      name: RSS
#      link: /feed.xml


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
